[programs.localnet]
coin98_gift = "7KZpqbt3uTD6DZ2gJpZRjTxVT6NULXVHYPcVw12ivBvE"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 test/*.spec.ts"
